// import { apiFetch } from './client';


export interface ExplanationFactor {
  label: string;
  value: string;
  impact: 'positive' | 'negative' | 'neutral';
}

export interface ExplainDecisionRequest {
  entity_type: 'incident' | 'site' | 'dispatch';
  entity_id: string;
}

export interface ExplainDecisionResponse {
  entity_id: string;
  summary: string;
  factors: ExplanationFactor[];
  generated_at: string;
}

export interface AuthorizeDispatchRequest {
  incident_id: string;
  assigned_user_id: string;
  resource_id?: string;
  notes: string;
  override_warnings?: boolean;
}

export interface AuthorizeDispatchResponse {
  dispatch_id: string;
  status: 'authorized' | 'rejected' | 'pending_review';
  message: string;
}

/**
 * Request an AI/Backend explanation for a specific incident or site.
 * Currently stubbed until backend endpoint is available.
 */
export async function explainDecision(req: ExplainDecisionRequest): Promise<ExplainDecisionResponse> {
  // TODO: Replace with real API call when backend endpoint is ready
  // const { data } = await apiClient.post<ExplainDecisionResponse>('/explain', req);
  // return data;
  
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve({
        entity_id: req.entity_id,
        summary: "This reasoning is generated by the AI decision engine based on live risk, resource pressure, and severity.",
        factors: [
          { label: "Severity Level", value: "Critical", impact: "negative" },
          { label: "Proximity to Safe Zone", value: "2.4 km", impact: "neutral" },
          { label: "Resource Availability", value: "Adequate", impact: "positive" }
        ],
        generated_at: new Date().toISOString()
      });
    }, 800);
  });
}

/**
 * Authorize a dispatch officially.
 * Currently stubbed until backend endpoint is available.
 */
export async function authorizeDispatch(req: AuthorizeDispatchRequest): Promise<AuthorizeDispatchResponse> {
  // TODO: Replace with real API call when backend endpoint is ready
  // const { data } = await apiClient.post<AuthorizeDispatchResponse>('/dispatch/authorize', req);
  // return data;
  
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      // Simulate backend validation rejection randomly or success
      resolve({
        dispatch_id: `dsp-${Math.random().toString().slice(2, 6)}`,
        status: 'authorized',
        message: 'Dispatch has been securely authorized and logged.'
      });
    }, 1000);
  });
}
