"""add_spatial_columns

Revision ID: a9b59bc70826
Revises: 42bb26f1b003
Create Date: 2026-08-20 14:36:10.173838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9b59bc70826'
down_revision: Union[str, Sequence[str], None] = '42bb26f1b003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


from app.models import Geometry

def upgrade() -> None:
    """Upgrade schema."""
    # Enable PostGIS on PostgreSQL
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS postgis;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('geom', Geometry(), nullable=True))
    op.add_column('rescue_sites', sa.Column('geom', Geometry(), nullable=True))
    op.add_column('zones', sa.Column('geom', Geometry(geometry_type='POLYGON'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zones', 'geom')
    op.drop_column('rescue_sites', 'geom')
    op.drop_column('incidents', 'geom')
    # ### end Alembic commands ###
